apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-concepts
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: aws=mguay22/nodejs-concepts:latest
    argocd-image-updater.argoproj.io/aws.update-strategy: digest
spec:
  destination:
    namespace: nodejs-concepts
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/mguay22/argocd-demo
    targetRevision: main
    path: apps/nodejs-concepts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
